name: Release Autofill-Form Extension

on:
  workflow_dispatch:
  push:
    branches: [ 1-ramzi-deployement ]

env:
  DIRECTORY: dist
  PROJECT_NAME: autofill-form

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - name: Build extension
        run: npm run build
      - name: Create version
        id: create_version
        run: |
          # Define the path to the version file
          VERSION_FILE="version.txt"

          # Check if the version file exists
          if [ -f "$VERSION_FILE" ]; then
            # Read the current version from the file
            VERSION=$(cat $VERSION_FILE)

            # Split the version into major, minor, and patch
            IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
            MAJOR=${VERSION_PARTS[0]}
            MINOR=${VERSION_PARTS[1]}
            PATCH=${VERSION_PARTS[2]}

            # Increment the patch version by 1
            PATCH=$((PATCH + 1))
            VERSION="$MAJOR.$MINOR.$PATCH"

            echo "Incrementing version to: $VERSION"
          else
            # Initialize the version if the file does not exist
            VERSION="1.0.0"
            echo "Setting initial version: $VERSION"
          fi

          # Save the new version to the version file
          echo "$VERSION" > $VERSION_FILE

          # Output the version to GitHub Actions
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: List files in dist directory
        run: ls -R $DIRECTORY
      - name: Update manifest.json
        run: |
          MANIFEST_PATH="$DIRECTORY/grat-extension/browser/manifest.json"
          if [ -f "$MANIFEST_PATH" ]; then
            sed -i 's/"version":.*/"version": "'${{ steps.create_version.outputs.version }}'",/' "$MANIFEST_PATH"
            echo "Updated manifest.json version to ${{ steps.create_version.outputs.version }}"
          else
            echo "Error: $MANIFEST_PATH not found"
            exit 1
          fi
      - name: Package extension
        run: |
          cd $DIRECTORY
          zip -r ../$PROJECT_NAME-${{ steps.create_version.outputs.version }}.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ${{ env.PROJECT_NAME }}-${{ steps.create_version.outputs.version }}.zip

  Firefox:
    needs: Build
    name: Submit to Firefox Add-ons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: extension
      - name: Install web-ext
        run: npm install -g web-ext@latest
      - name: Unzip extension
        run: unzip ${{ env.PROJECT_NAME }}-${{ needs.Build.outputs.version }}.zip -d extension_dir
      - name: Sign and submit to Firefox Add-ons
        run: |
          cd extension_dir/grat-extension/browser
          web-ext sign --channel listed --source-dir .
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
