name: Release Autofill-Form Extension

on:
  workflow_dispatch:

env:
  PROJECT_NAME: autofill-form

jobs:
  build-and-submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Increment version and update manifest
        id: version
        run: |
          MANIFEST_PATH="dist/grat-extension/browser/manifest.json"
          CURRENT_VERSION=$(jq -r '.version' "$MANIFEST_PATH")
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          ((VERSION_PARTS[2]++))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          jq ".version = \"$NEW_VERSION\"" "$MANIFEST_PATH" > temp.json && mv temp.json "$MANIFEST_PATH"
          echo "Version incremented from $CURRENT_VERSION to $NEW_VERSION"

      - name: Package extension
        run: |
          cd dist
          zip -r ../${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version }}.zip .

      - name: Sign and submit to Firefox Add-ons
        run: npx web-ext sign --channel listed --source-dir .
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
