name: Deploy Firefox Extension

on:
  push:
    branches: [ deploy-on-addons ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the extension
        run: npm run build

      - name: Package the extension
        run: |
          cd dist/grat-extension
          zip -r ../../extension.zip .

      - name: Upload the extension
        uses: mozilla/web-ext-action@v2
        with:
          api-key: ${{ secrets.AMO_API_KEY }}
          api-secret: ${{ secrets.AMO_API_SECRET }}
          source-dir: dist/grat-extension
          artifact: extension.zip
          id: 'teberramzi@gmail.com'
