name: Deploy to Mozilla Add-ons

on:
  push:
    branches: [ deploy-on-addons ]

jobs:
  build-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build # Assurez-vous d'avoir une commande de build définie dans votre package.json

      - name: Debug build output
        run: ls -R dist

      - name: Package extension
        run: zip -r extension.zip dist

      - name: Deploy to Mozilla Add-ons
        uses: trmcnvn/firefox-addon@v1
        with:
          uuid: 'teberramzi@gmail.com'
          xpi: extension.zip
          manifest: dist/manifest.json
          api-key: ${{ secrets.AMO_JWT_ISSUER }}
          api-secret: ${{ secrets.AMO_JWT_SECRET }}
